= Reproducible Builds Gradle plugin

image:https://github.com/gradlex-org/reproducible-builds/actions/workflows/ci-build.yml/badge.svg["CI Build", link="https://github.com/gradlex-org/reproducible-builds/actions/workflows/ci-build.yml"]
image:https://img.shields.io/gradle-plugin-portal/v/org.gradlex.reproducible-builds?label=Plugin%20Portal["Gradle Plugin Portal", link="https://plugins.gradle.org/plugin/org.gradlex.reproducible-builds"]

Reproducibility settings applied to some of Gradle's built-in tasks, that should really be the default.
Compatible with Java 8 and Gradle 8.3 or later.

== Usage

Apply this plugin to all projects in your build, and it configures archive and compilation tasks for reproducibility.

[source.multi-language-sample,kotlin]
----
plugins {
    id("org.gradlex.reproducible-builds")
}
----
[source.multi-language-sample,groovy]
----
plugins {
    id 'org.gradlex.reproducible-builds'
}
----

== What this plugin does

This sections explains each of the configurations the plugin applies to your build.

=== Compilation tasks

.Table Configuration applied to tasks of type `JavaCompile`, `JavaDoc`, `GroovyCompile`, and `ScalaCompile`
|===
|Setting|Value|Explanation

|`options.encoding`
|`UTF_8`
|If not configured, the platform encoding is used.

|`options.fork`
|`true`
|Required, so that fork options always take effect.

|`forkOptions.jvmArgumentProviders`
|`add("-Dline.separator=\n")`
|Use `\n` as file separator for files generated by annotation processors
|===

=== Archive tasks (Gradle 8.x only)

NOTE: Since 9.0.0, Gradle core https://docs.gradle.org/current/userguide/upgrading_major_version_9.html#reproducible_archives_by_default[covers this aspect of reproducibility directly]

.Table Configuration applied to tasks of type `AbstractArchiveTask`
|===
|Setting|Value|Explanation

|`preserveFileTimestamps`
|`false`
|If not configured, files inside the archive will have timestamps related to when the files were created.

|`reproducibleFileOrder`
|`true`
|If not configured, the order of entries in the archive depends on the underlying filesystem of the machine that creates the archive.

|`dirPermissions`
|`unix("755")`
| If not configured, permissions are influence by the operating system on which the build is running and usually differ between Unix and Windows.

|`filePermissions`
|`unix("644")`
| If not configured, permissions are influence by the operating system on which the build is running and usually differ between Unix and Windows.
|===
